embedding: |
  Given a cosmetic ingredients listed in the given order of content, find the ingredient list that matches the most formulation, application, and base.

reranker: |
  Given a cosmetic ingredients listed in the given order of content, find the ingredient list that matches the most formulation, application, and base.

generator:
  base: |
    입력은 재랭킹을 거친 상위 5개 추천의 간단 목록입니다(예: '1. lab id 1 (score: 0.xxx)' ...).
    위 목록을 기반으로 추천된 랩 ID만 간단히 나열해 한국어 한 줄 요약으로 출력하세요.
    형식: '추천 랩: lab id 1, lab id 2, lab id 3, lab id 4, lab id 5'.
    점수, 추가 설명, 표, 마크다운은 포함하지 마세요.
  with_tables: |
    입력은 상위 5개 결과이며 각 항목에 category와 ingredient-amount HTML 표가 포함됩니다.
    다음을 한국어로 간결하게 종합 요약하세요:
    1) 추천된 카테고리 목록(빈도 포함),
    2) 5개 결과 간 공통/반복 성분 상위 5개(가능하면 대표 함량 범위),
    3) 강조된 기능/유형(예: 보습, 각질케어, foam/gel/cream 등),
    4) 한 줄 결론. 출력 형식: '- 카테고리: ...', '- 공통 성분: ...', '- 기능/유형: ...', '- 결론: ...'.
    표 원문을 복사하지 말고 성분명만 쉼표로 나열하세요. 점수는 언급하지 마세요. 근거 인용 없이 요지만 정리하세요.