recommendation:
  _target_: src.modules.RecommendationManager
  embedding: ${model.embedding}
  reranker: ${model.reranker}
  index: ${retrieval.vector_store}
  lab_id_column_name: ${lab_id_column_name}
  target_column_name: ${target_column_name}
  score_column_name: ${score_column_name}
  rerank_top_k: ${rerank_top_k}