# @package _global_
defaults:
  - database: vector_store
  - model: model
  - manager: manager
  - hydra: hydra

package_name: recipe-ai-test
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}
usage: RecipeAI

seed: 2025

data_path: ${connected_dir}/data
indices_name: recipe_db.faiss
items_name: recipe_db.csv

lab_id_column_name: lab_no
category_column_name: category
category_name_column_name: category_name
target_column_name: ingredient_en
amount_column_name: amount

distance_column_name: distance
score_column_name: score

role_column_name: role
content_column_name: content

model_family: Qwen/Qwen3
model_id:
  embedding: ${model_family}-Embedding-4B
  reranker: ${model_family}-Reranker-4B
  generator: ${model_family}-8B

dim: 2560
num_gpus: ${oc.decode:${oc.env:DEVICES}}

gpu_memory_utilization:
  embedding: 0.45
  reranker: 0.45
  generator: 0.9

max_length: 4096
generator_max_length: 16384
max_new_tokens: 2048
do_sample: true
generation_config:
  temperature: 0.6
  top_p: 0.95
  top_k: 20

instruction:
  embedding: "Given a cosmetic ingredients listed in the given order of content, find the ingredient list that matches the most formulation, application, and base."
  reranker: "Given a cosmetic ingredients listed in the given order of content, find the ingredient list that matches the most formulation, application, and base."
  generator:
    base: "입력은 재랭킹을 거친 상위 5개 추천의 간단 목록입니다(예: '1. lab id 1 (score: 0.xxx)' ...). 위 목록을 기반으로 추천된 랩 ID만 간단히 나열해 한국어 한 줄 요약으로 출력하세요. 형식: '추천 랩: lab id 1, lab id 2, lab id 3, lab id 4, lab id 5'. 점수, 추가 설명, 표, 마크다운은 포함하지 마세요."
    with_tables: "입력은 상위 5개 결과이며 각 항목에 category와 ingredient-amount HTML 표가 포함됩니다. 다음을 한국어로 간결하게 종합 요약하세요: 1) 추천된 카테고리 목록(빈도 포함), 2) 5개 결과 간 공통/반복 성분 상위 5개(가능하면 대표 함량 범위), 3) 강조된 기능/유형(예: 보습, 각질케어, foam/gel/cream 등), 4) 한 줄 결론. 출력 형식: '- 카테고리: ...', '- 공통 성분: ...', '- 기능/유형: ...', '- 결론: ...'. 표 원문을 복사하지 말고 성분명만 쉼표로 나열하세요. 점수는 언급하지 마세요. 근거 인용 없이 요지만 정리하세요."

top_k:
  retrieval: 50
  rerank: 5

device_id:
  embedding: 0
  reranker: 0
  generator: 1
master_addr: 127.0.0.1
master_port:
  embedding: 29501
  reranker: 29511
  generator: 29521
nccl_socket_ifname: lo
nccl_ib_disable: 1

input_mode:
  lab_id: 1
  ingredients: 2

is_table: true

project_name: ${package_name}-${usage}

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}